@url_dev=http://localhost:8080/v1/api
###signup

POST {{url_dev}}/shop/signup
content-type: application/json

{
    "email": "long02@gmail.com",
    "name": "Longby",
    "password": "12345"
}